import{AGENT_PROFILES,AgentId,AgentTask,AgentEvent,agentOrchestrator}from"./agentOrchestrator";import{requestApproval}from"./approvalGate";
export type RuntimeResult={taskId:string,agent:AgentId,summary:string,nextAgent?:AgentId,needsApproval?:boolean};
const specialist=(goal:string):AgentId=>{const g=goal.toLowerCase();if(/pesquis|notícia|mercado|empresa|oportunidade/.test(g))return"researcher";if(/site|código|github|app|program/.test(g))return"builder";if(/venda|cliente|crm|negócio|proposta/.test(g))return"business";if(/câmera|rosto|imagem|visão|tela/.test(g))return"vision";if(/computador|abrir|clicar|executar/.test(g))return"operator";return"analyst"};
export class MultiAgentRuntime{
 private queue:string[]=[];private running=false;
 submit(goal:string){const root=agentOrchestrator.create(goal,"normal");this.queue.push(root.id);this.pump();return root}
 private async pump(){if(this.running)return;this.running=true;try{while(this.queue.length){const id=this.queue.shift()!;const task=agentOrchestrator.list().find(t=>t.id===id);if(!task)continue;if(task.agent==="core"){const a=specialist(task.goal);agentOrchestrator.assign(id,"planner");const child=agentOrchestrator.create("Executar: "+task.goal,"normal",id);agentOrchestrator.assign(child.id,a);this.queue.push(child.id);agentOrchestrator.complete(id,"Fluxo delegado ao Planner e ao especialista "+a+"; aguardando consolidação.");continue}const profile=AGENT_PROFILES.find(a=>a.id===task.agent);if(!profile)continue;if(profile.canAct){const approval=requestApproval("Executar tarefa do agente "+profile.name,"medium",task.goal);agentOrchestrator.emit?.(id,"approval.required","Aprovação necessária: "+approval.id);agentOrchestrator.fail(id,"Bloqueado até aprovação explícita: "+approval.id);continue}agentOrchestrator.complete(id,"Especialista "+profile.name+" concluiu a etapa e devolveu o resultado ao Core.");}}finally{this.running=false}}
}
export const multiAgentRuntime=new MultiAgentRuntime();
