export type GoalStatus="active"|"paused"|"completed";
export type Goal={id:string;title:string;why?:string;status:GoalStatus;progress:number;createdAt:string;updatedAt:string;milestones:string[]};
export type OpportunityScore={id:string;name:string;score:number;reason:string;nextAction:string;source?:string};
export type CouncilMember={id:string;name:string;role:string;decision:string;confidence:number};
export type Simulation={id:string;goal:string;actions:string[];risks:string[];permissions:string[];reversible:boolean;score:number;createdAt:string};
export type SkillProposal={id:string;name:string;gap:string;steps:string[];permissions:string[];tests:string[];status:"pending"|"approved"|"rejected"|"activated";createdAt:string};
export type Anticipation={id:string;title:string;detail:string;priority:"low"|"medium"|"high";action:string;createdAt:string};
const read=<T,>(k:string,d:T):T=>{try{return JSON.parse(localStorage.getItem(k)||"null")??d}catch{return d}};
const write=(k:string,v:unknown)=>localStorage.setItem(k,JSON.stringify(v));
const keys={goals:"jarvis.goals.v1",sims:"jarvis.simulations.v1",skills:"jarvis.skills.factory.v1",anticipation:"jarvis.anticipation.v1"};
export function createGoal(title:string,why=""):Goal{const now=new Date().toISOString();const g:Goal={id:crypto.randomUUID(),title:title.trim(),why,status:"active",progress:0,createdAt:now,updatedAt:now,milestones:["Definir resultado","Pesquisar contexto","Escolher estratégia","Executar ações aprovadas","Medir resultado","Registrar aprendizado"]};write(keys.goals,[g,...read<Goal[]>(keys.goals,[])]);return g}
export function listGoals(){return read<Goal[]>(keys.goals,[])}
export function updateGoal(id:string,patch:Partial<Goal>){const v=read<Goal[]>(keys.goals,[]).map(g=>g.id===id?{...g,...patch,updatedAt:new Date().toISOString()}:g);write(keys.goals,v);return v.find(g=>g.id===id)}
export function rankOpportunities():OpportunityScore[]{const opps=read<any[]>("az:opps",[]);return opps.map((o,i)=>{const text=String(o.name||o.title||o.businessName||"Oportunidade "+(i+1));const raw=Number(o.score??o.potential??0);const score=Math.max(1,Math.min(100,Math.round(raw||55+(i%5)*7)));return{id:String(o.id||i),name:text,score,reason:score>=75?"alto potencial com prioridade de validação":"vale investigar antes de abordar",nextAction:score>=75?"pesquisar presença digital e preparar diagnóstico":"coletar mais evidências",source:o.source}}).sort((a,b)=>b.score-a.score)}
export function buildCouncil(goal:string):CouncilMember[]{const g=goal.toLowerCase();const external=/pesquis|site|empresa|cliente|venda|internet/.test(g);return[{id:"researcher",name:"Researcher",role:"Evidências",decision:external?"Pesquisar fontes públicas e contexto antes de agir.":"Pesquisar o contexto necessário.",confidence:.9},{id:"strategist",name:"Strategist",role:"Estratégia",decision:"Escolher o caminho com maior valor e menor complexidade.",confidence:.88},{id:"builder",name:"Builder",role:"Construção",decision:"Preparar a menor implementação verificável.",confidence:.82},{id:"analyst",name:"Analyst",role:"Métricas",decision:"Definir como saberemos se funcionou.",confidence:.86},{id:"sentinel",name:"Sentinel",role:"Segurança",decision:"Bloquear ações externas sem aprovação explícita.",confidence:.98}]}
export function simulateExecution(goal:string):Simulation{const s:Simulation={id:crypto.randomUUID(),goal:goal.trim(),actions:["Entender o resultado esperado","Pesquisar apenas contexto autorizado","Montar plano em etapas","Executar ações locais seguras","Solicitar aprovação para ações externas","Verificar o resultado","Registrar aprendizado"],risks:["Dados externos podem estar incompletos","Integrações podem falhar","Ações externas permanecem bloqueadas sem aprovação"],permissions:["Pesquisa pública autorizada","Ações locais seguras","Aprovação humana para ações externas"],reversible:true,score:82,createdAt:new Date().toISOString()};write(keys.sims,[s,...read<Simulation[]>(keys.sims,[])]);return s}
export function listSimulations(){return read<Simulation[]>(keys.sims,[])}
export function proposeSkill(task:string):SkillProposal{const s:SkillProposal={id:crypto.randomUUID(),name:"Skill: "+task.trim().slice(0,60),gap:"Capacidade ainda não disponível no conjunto atual.",steps:["Definir contrato da ferramenta","Pesquisar integração reutilizável","Implementar isolamento e permissões","Testar em sandbox","Validar com Sentinel","Ativar somente após aprovação"],permissions:["Aprovação para implementar","Aprovação separada para ações externas de impacto"],tests:["Teste unitário","Teste de sandbox","Teste de falha","Teste de rollback"],status:"pending",createdAt:new Date().toISOString()};write(keys.skills,[s,...read<SkillProposal[]>(keys.skills,[])]);return s}
export function listSkillProposals(){return read<SkillProposal[]>(keys.skills,[])}
export function setSkillStatus(id:string,status:SkillProposal["status"]){const v=read<SkillProposal[]>(keys.skills,[]).map(s=>s.id===id?{...s,status}:s);write(keys.skills,v);return v.find(s=>s.id===id)}
export function scanAnticipation():Anticipation[]{const goals=listGoals(),opps=rankOpportunities(),tasks=read<any[]>("az:tasks",[]),items:Anticipation[]=[];if(opps.length)items.push({id:"opp",title:"Há oportunidades que merecem priorização",detail:opps.slice(0,3).map(o=>o.name).join(" · "),priority:opps[0].score>=75?"high":"medium",action:"Abrir Opportunity Radar",createdAt:new Date().toISOString()});if(tasks.length>=3)items.push({id:"tasks",title:"Existem tarefas repetidas",detail:"Tarefas recorrentes podem virar uma Skill revisável.",priority:"medium",action:"Criar proposta de Skill",createdAt:new Date().toISOString()});if(goals.some(g=>g.status==="active"&&g.progress===0))items.push({id:"goal",title:"Existe objetivo sem progresso registrado",detail:"O próximo passo é transformar o objetivo em uma missão executável.",priority:"high",action:"Avançar objetivo",createdAt:new Date().toISOString()});write(keys.anticipation,items);return items}
export function listAnticipations(){return read<Anticipation[]>(keys.anticipation,[])}
export function memoryCognition(text:string){const words=text.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").split(/\s+/).filter(w=>w.length>4);const importance=Math.min(1,.35+Math.min(.5,words.length/40));return{summary:text.trim().replace(/\s+/g," ").slice(0,220),importance,keywords:[...new Set(words)].slice(0,8),why:importance>=.7?"contexto potencialmente persistente":"relevância moderada"}}
