import{useEffect,useState}from"react";
import{Target,Search,Users,Shield,Play,BrainCircuit,Sparkles,ArrowRight,CheckCircle2,RefreshCw}from"lucide-react";
import{buildCouncil,createGoal,listGoals,rankOpportunities,simulateExecution,listSimulations,proposeSkill,listSkillProposals,setSkillStatus,scanAnticipation,updateGoal,type Goal,type OpportunityScore,type Simulation,type SkillProposal,type Anticipation}from"../services/jarvisAdvanced";
export function JarvisAdvanced(){const[goal,setGoal]=useState("");const[goals,setGoals]=useState<Goal[]>([]);const[opps,setOpps]=useState<OpportunityScore[]>([]);const[council,setCouncil]=useState<any[]>([]);const[sim,setSim]=useState<Simulation|null>(null);const[sims,setSims]=useState<Simulation[]>([]);const[skills,setSkills]=useState<SkillProposal[]>([]);const[ants,setAnts]=useState<Anticipation[]>([]);const[notice,setNotice]=useState("");
const refresh=()=>{setGoals(listGoals());setOpps(rankOpportunities());setSims(listSimulations());setSkills(listSkillProposals());setAnts(scanAnticipation())};useEffect(refresh,[]);
const startGoal=()=>{if(!goal.trim())return;createGoal(goal);setCouncil(buildCouncil(goal));setSim(simulateExecution(goal));setGoal("");setNotice("Objetivo criado. O plano foi simulado e aguarda execução autorizada.");refresh()};
const newSkill=()=>{proposeSkill(goal||"esta capacidade");setGoal("");setNotice("Proposta de Skill criada e bloqueada até aprovação.");refresh()};
return <div className="content" style={{padding:0}}><div className="pagehead"><div><span className="eyebrow">JARVIS // ADVANCED CORE</span><h1>Centro de Inteligência</h1><p>Objetivos, oportunidades, conselho de agentes, simulação, antecipação e evolução.</p></div><button className="primary" onClick={refresh}><RefreshCw size={16}/> Atualizar núcleo</button></div>
{notice&&<div className="notice"><CheckCircle2 size={16}/> {notice}</div>}
<section className="panel" style={{marginBottom:18}}><div className="panelhead"><div><span className="eyebrow">01 // OBJECTIVE MODE</span><h2>Transforme uma frase em missão</h2></div><Target size={19}/></div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><input className="input" style={{flex:1,minWidth:240}} value={goal} onChange={e=>setGoal(e.target.value)} placeholder='Ex.: "Quero conseguir meus primeiros R$1.000 com sites"'/><button className="primary" onClick={startGoal}><Play size={15}/> Criar objetivo</button><button className="ghost" onClick={newSkill}><Sparkles size={15}/> Criar Skill</button></div></section>
<div className="grid2"><section className="panel"><div className="panelhead"><div><span className="eyebrow">02 // OPPORTUNITY RADAR</span><h2>Oportunidades priorizadas</h2></div><Search size={18}/></div>{opps.length?opps.slice(0,6).map(o=><div className="event" key={o.id}><div className="eventdot"/><div style={{flex:1}}><b>{o.name}</b><p>{o.reason}</p><small>Próximo: {o.nextAction}</small></div><strong>{o.score}</strong></div>):<div className="jEmpty">Faça uma pesquisa de oportunidades para alimentar o radar.</div>}</section>
<section className="panel"><div className="panelhead"><div><span className="eyebrow">03 // ANTICIPATION</span><h2>O que JARVIS percebeu</h2></div><BrainCircuit size={18}/></div>{ants.length?ants.map(a=><div className="event" key={a.id}><div className="eventdot"/><div><b>{a.title}</b><p>{a.detail}</p><small>{a.priority.toUpperCase()} · {a.action}</small></div></div>):<div className="jEmpty">Nenhuma antecipação relevante no momento.</div>}</section></div>
<section className="panel" style={{marginTop:18}}><div className="panelhead"><div><span className="eyebrow">04 // AGENT COUNCIL</span><h2>{council.length?"Conselho analisando objetivo":"Conselho em espera"}</h2></div><Users size={18}/></div>{council.length?council.map(c=><div className="event" key={c.id}><div className="eventdot"/><div style={{flex:1}}><b>{c.name} · {c.role}</b><p>{c.decision}</p></div><small>{Math.round(c.confidence*100)}%</small></div>):<div className="jEmpty">Crie um objetivo para convocar os especialistas.</div>}</section>
<div className="grid2" style={{marginTop:18}}><section className="panel"><div className="panelhead"><div><span className="eyebrow">05 // PRE-EXECUTION SIMULATOR</span><h2>Plano antes da ação</h2></div><Shield size={18}/></div>{sim?<><div className="notice"><b>{sim.score}/100</b> · plano reversível · aprovação humana para ações externas</div>{sim.actions.map((x,i)=><div className="event" key={x}><div className="eventdot"/><div><b>{String(i+1).padStart(2,"0")} {x}</b></div></div>)}<div className="tags">{sim.risks.map(r=><span key={r}>{r}</span>)}</div></>:<div className="jEmpty">Nenhum plano simulado ainda.</div>}</section>
<section className="panel"><div className="panelhead"><div><span className="eyebrow">06 // SKILL FACTORY</span><h2>Capacidades novas</h2></div><Sparkles size={18}/></div>{skills.length?skills.slice(0,5).map(s=><div className="event" key={s.id}><div className="eventdot"/><div style={{flex:1}}><b>{s.name}</b><p>{s.gap}</p><small>{s.status.toUpperCase()}</small></div>{s.status==="pending"&&<button className="ghost" onClick={()=>{setSkillStatus(s.id,"approved");refresh()}}>Aprovar</button>}{s.status==="approved"&&<button className="primary" onClick={()=>{setSkillStatus(s.id,"activated");refresh()}}>Ativar</button>}</div>):<div className="jEmpty">Nenhuma Skill proposta.</div>}</section></div>
<section className="panel" style={{marginTop:18}}><div className="panelhead"><div><span className="eyebrow">07 // ACTIVE OBJECTIVES</span><h2>Objetivos persistentes</h2></div><ArrowRight size={18}/></div>{goals.length?goals.map(g=><div className="event" key={g.id}><div className="eventdot"/><div style={{flex:1}}><b>{g.title}</b><p>{g.status.toUpperCase()} · {g.progress}%</p><div style={{height:5,background:"rgba(255,255,255,.08)",borderRadius:9}}><div style={{height:"100%",width:g.progress+"%",background:"currentColor",borderRadius:9}}/></div></div>{g.status==="active"&&<button className="ghost" onClick={()=>{updateGoal(g.id,{progress:Math.min(100,g.progress+20),status:g.progress>=80?"completed":"active"});refresh()}}><CheckCircle2 size={14}/> Avançar</button>}</div>):<div className="jEmpty">Nenhum objetivo criado.</div>}</section>
{sims.length>1&&<div className="muted" style={{marginTop:12}}>Simulações salvas: {sims.length}. Cada uma permanece registrada para auditoria.</div>}
</div>}
