import{useEffect,useRef,useState}from"react";
import{Activity,BrainCircuit,Camera,ChevronRight,Command,Eye,LockKeyhole,Mic,Network,Radio,Shield,Terminal,UserRound,Volume2,X,Zap}from"lucide-react";
import{createActionPlanWithAI,type JarvisActionPlan}from"../services/jarvisActionPlan";
import{multiAgentRuntime}from"../services/agentRuntime";
import{discoverUnknown}from"../services/jarvisUnknown";

type Props={go:(p:string)=>void;addApproval:(a:any)=>void};
type Log={id:string;time:string;text:string;kind:string};
const save=(x:Log[])=>localStorage.setItem("jarvis.session.logs",JSON.stringify(x.slice(0,30)));
const load=():Log[]=>{try{return JSON.parse(localStorage.getItem("jarvis.session.logs")||"[]")}catch{return[]}};
const speak=(text:string)=>{try{window.speechSynthesis?.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="pt-BR";u.rate=.92;u.pitch=.88;window.speechSynthesis?.speak(u)}catch{}};
const cinematicTone=()=>{try{const C=window.AudioContext||(window as any).webkitAudioContext;if(!C)return;const c=new C();const now=c.currentTime;[220,330,440,660].forEach((f,i)=>{const o=c.createOscillator();const g=c.createGain();o.type="sine";o.frequency.value=f;o.connect(g);g.connect(c.destination);g.gain.setValueAtTime(.0001,now+i*.11);g.gain.exponentialRampToValueAtTime(.045,now+i*.11+.03);g.gain.exponentialRampToValueAtTime(.0001,now+i*.11+.65);o.start(now+i*.11);o.stop(now+i*.11+.7)});setTimeout(()=>c.close(),1400)}catch{}};

export function JarvisOS({go,addApproval}:Props){
 const[cmd,setCmd]=useState("");const[status,setStatus]=useState("READY");const[plan,setPlan]=useState<JarvisActionPlan|null>(null);const[logs,setLogs]=useState<Log[]>(load);const[thinking,setThinking]=useState(false);const[time,setTime]=useState(new Date());const[voice,setVoice]=useState(false);
 const[name,setName]=useState(()=>localStorage.getItem("jarvis.user.name")||"");const[identityOpen,setIdentityOpen]=useState(()=>!localStorage.getItem("jarvis.identity.setup"));const[faceReady,setFaceReady]=useState(false);const[faceChecking,setFaceChecking]=useState(false);const[stream,setStream]=useState<MediaStream|null>(null);const videoRef=useRef<HTMLVideoElement>(null);
 useEffect(()=>{const id=setInterval(()=>setTime(new Date()),1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(videoRef.current&&stream)videoRef.current.srcObject=stream},[stream]);
 const push=(text:string,kind="SYSTEM")=>{const x={id:crypto.randomUUID(),time:new Date().toLocaleTimeString("pt-BR"),text,kind};setLogs(v=>{const n=[x,...v];save(n);return n})};
 const beginIdentity=async()=>{if(!name.trim())return;localStorage.setItem("jarvis.user.name",name.trim());setFaceChecking(true);cinematicTone();push("Inicializando sessão de identidade local.","IDENTITY");try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user"},audio:false});setStream(s);setFaceReady(true);await new Promise(r=>setTimeout(r,900));push("Câmera autorizada. Nenhuma imagem foi enviada ou salva.","IDENTITY")}catch{push("Câmera não autorizada. A sessão continuará sem verificação facial.","GUARD")}setFaceChecking(false);setIdentityOpen(false);localStorage.setItem("jarvis.identity.setup","1");setStatus("READY");setTimeout(()=>speak(`Bom te ver, ${name.trim()}. JARVIS online.`),350)};
 const closeCamera=()=>{stream?.getTracks().forEach(t=>t.stop());setStream(null)};
 const run=async(input:string)=>{if(!input.trim()||thinking)return;setCmd("");setThinking(true);setStatus("ANALYZING");push(input,"YOU");const base=localStorage.getItem("az:executorUrl")||"http://localhost:8787";const p=await createActionPlanWithAI(input,base);
  if(!p){setStatus("OFFLINE FALLBACK");push("Não foi possível consultar o Action Planner. Use o Intent Engine local ou conecte o Worker + API.","GUARD");setThinking(false);return}
  setPlan(p);push(p.summary,"PLAN");setStatus(p.requiresApproval?"AWAITING APPROVAL":"EXECUTING");
  for(const a of p.actions){if(a.type==="navigate"){go(a.path);push("Navegando para "+a.path,"ACTION")}
   if(a.type==="worker_health"){try{const h=await fetch(base+"/health",{signal:AbortSignal.timeout(3000)});const d=await h.json();push("Worker conectado: "+d.status,"ACTION")}catch{push("Worker local indisponível.","GUARD")}}
   if(a.type==="delegate"){const t=multiAgentRuntime.submit(a.goal);push("Missão delegada ao agente runtime: "+t.id.slice(0,8),"AGENT")}
   if(a.type==="open_url"||a.type==="inspect_site"){addApproval({id:crypto.randomUUID(),type:"execução de navegador",title:a.label,description:"Ação externa preparada pelo Action Planner. Requer aprovação explícita.",createdAt:new Date().toISOString(),status:"pending",execution:{type:a.type,url:a.url}});push("Ação externa bloqueada até aprovação.","GUARD");go("/aprovacoes")}
  }setStatus(p.requiresApproval?"AWAITING APPROVAL":"READY");setThinking(false)
 };
 const unknown=discoverUnknown();
 return <div className="jarvisOS"><div className="jarvisOSNoise"/>
  {identityOpen&&<div className="jarvisIdentityGate"><div className="jarvisIdentityBox"><button className="identityClose" onClick={()=>{setIdentityOpen(false);localStorage.setItem("jarvis.identity.setup","1")}}><X size={16}/></button><div className="identityOrb"><UserRound size={25}/><span/></div><span className="eyebrow">FIRST CONTACT // LOCAL IDENTITY</span><h1>Como devo te chamar?</h1><p>Escolha o nome que JARVIS usará para falar com você. A câmera é opcional e fica somente no dispositivo durante esta sessão.</p><div className="identityName"><UserRound size={16}/><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Seu nome ou apelido"/></div><div className={"faceCheck "+(faceReady?"ready":"")}><Camera size={17}/><div><b>{faceChecking?"VERIFICANDO CÂMERA...":faceReady?"CÂMERA PRONTA":"VERIFICAÇÃO FACIAL OPCIONAL"}</b><small>Sem upload. Sem armazenamento de imagem.</small></div></div><button className="identityStart" disabled={!name.trim()||faceChecking} onClick={beginIdentity}>{faceChecking?"INICIALIZANDO...":"ENTRAR NO JARVIS"} <ChevronRight size={15}/></button></div></div>}
  <header className="jarvisOSHeader"><div className="jarvisOSBrand"><div className="jarvisOSMark"><Radio size={18}/></div><div><b>J.A.R.V.I.S.</b><span>PERSONAL INTELLIGENCE OPERATING SYSTEM</span></div></div><div className="jarvisOSWelcome">{name&&<><UserRound size={12}/> {name.toUpperCase()}</>}</div><div className="jarvisOSClock">{time.toLocaleTimeString("pt-BR")}<small>LOCAL SESSION</small></div><button className="jarvisOSExit" onClick={()=>{closeCamera();go("/")}}>AGENTE ZERO <ChevronRight size={13}/></button></header>
  <div className="jarvisOSGrid"><aside className="jarvisOSRail"><button onClick={()=>go("/jarvis")} className="active"><BrainCircuit/><span>CORE</span></button><button onClick={()=>go("/runtime")}><Network/><span>AGENTS</span></button><button onClick={()=>go("/visao")}><Eye/><span>VISION</span></button><button onClick={()=>go("/memoria")}><Activity/><span>MEMORY</span></button><button onClick={()=>go("/aprovacoes")}><Shield/><span>GUARD</span></button><button onClick={()=>go("/execucao")}><Terminal/><span>OPS</span></button></aside>
   <main className="jarvisOSMain"><div className="jarvisOSTelemetry"><span>CORE <b>ONLINE</b></span><span>LOCAL <b>ENCRYPTED</b></span><span>GUARD <b>DEFAULT DENY</b></span><span>MODE <b>HUMAN IN LOOP</b></span></div>
    <section className={"jarvisReactor "+(thinking?"reacting":"")}><div className="reactorOrbit o1"/><div className="reactorOrbit o2"/><div className="reactorOrbit o3"/><div className="reactorCore"><BrainCircuit size={32}/><b>{status}</b><small>JARVIS CORE</small></div></section>
    <section className="jarvisMission"><span className="eyebrow">MISSION INTERFACE // ACTION PLANNER</span><h1>{thinking?"Deixe-me estruturar isso.":name?`Olá, ${name}. O que vamos fazer?`:"O que você quer que eu descubra?"}</h1><p>Fale naturalmente. JARVIS interpreta o objetivo, cria um plano, coordena agentes e para diante de qualquer ação que precise da sua autorização.</p><form onSubmit={e=>{e.preventDefault();run(cmd)}}><Command size={17}/><input value={cmd} onChange={e=>setCmd(e.target.value)} placeholder="Ex.: encontre uma oportunidade e monte um plano para ela"/><button disabled={thinking}><Zap size={17}/></button></form></section>
    <section className="jarvisPanels"><div className="jarvisPanel"><div className="jPanelTitle"><span>NEURAL PLAN</span><b>{plan?Math.round(plan.confidence*100)+"% CONFIDENCE":"STANDBY"}</b></div>{plan?<><h2>{plan.summary}</h2><p>{plan.reason||"Plano gerado pelo Action Planner."}</p><div className="jSteps">{plan.actions.map((a,i)=><div key={i}><i>{String(i+1).padStart(2,"0")}</i><span>{a.label}</span><small>{a.type.replaceAll("_"," ")}</small></div>)}</div></>:<div className="jEmpty">Nenhuma missão ativa. O núcleo está observando o contexto autorizado.</div>}</div>
     <div className="jarvisPanel"><div className="jPanelTitle"><span>LIVE EVENT STREAM</span><b>{logs.length} EVENTS</b></div><div className="jLogs">{logs.slice(0,7).map(l=><div key={l.id}><time>{l.time}</time><strong>{l.kind}</strong><span>{l.text}</span></div>)}</div></div></section>
    <section className="jarvisBottom"><div><span className="eyebrow">UNKNOWN ENGINE</span><b>{unknown?"ENCONTREI ALGO PARA INVESTIGAR":"SCANNING SYSTEM STATE"}</b><p>{unknown?.title||"Observando conexões entre memória, tarefas, oportunidades e habilidades."}</p></div><button onClick={()=>run("JARVIS, me surpreenda")}>SURPRISE ME <Zap size={14}/></button><div className="jHealth"><span><LockKeyhole size={13}/> APPROVAL GATE</span><span><Volume2 size={13}/> VOICE READY</span><span><Camera size={13}/> {faceReady?"FACE CHECK READY":"FACE CHECK OPTIONAL"}</span><button onClick={()=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){push("Reconhecimento de voz não suportado neste navegador.","GUARD");return}const r=new SR();r.lang="pt-BR";r.continuous=false;r.interimResults=false;setVoice(true);setStatus("LISTENING");r.onresult=(e:any)=>{setVoice(false);setStatus("ANALYZING");run(e.results[0][0].transcript)};r.onerror=()=>{setVoice(false);setStatus("READY")};r.onend=()=>setVoice(false);r.start()}}><Mic size={13}/> {voice?"LISTENING":"TALK TO JARVIS"}</button></div></section>
   </main></div>
  {stream&&<div className="jarvisFaceMini"><video ref={videoRef} autoPlay muted playsInline/><div><Camera size={11}/> LOCAL FACE CHECK <button onClick={closeCamera}>STOP</button></div></div>}
 </div>
}
