import{useEffect,useRef,useState}from"react";
import{Activity,BrainCircuit,Camera,ChevronRight,Eye,LockKeyhole,Mic,Music2,Network,Radio,Shield,Terminal,UserRound,Volume2,X,Zap}from"lucide-react";
import{createActionPlanWithAI,type JarvisActionPlan}from"../services/jarvisActionPlan";
import{multiAgentRuntime}from"../services/agentRuntime";
import{discoverUnknown}from"../services/jarvisUnknown";
import{studyCapabilityGap}from"../services/jarvisEvolution";
import{startJarvisAmbient,stopJarvisAmbient}from"../services/jarvisAmbient";
import{rememberIfImportant}from"../services/jarvisMemory";

type Props={go:(p:string)=>void;addApproval:(a:any)=>void};
type Log={id:string;time:string;text:string;kind:string};
const save=(x:Log[])=>localStorage.setItem("jarvis.session.logs",JSON.stringify(x.slice(0,30)));
const load=():Log[]=>{try{return JSON.parse(localStorage.getItem("jarvis.session.logs")||"[]")}catch{return[]}};
const speak=(text:string)=>{try{window.speechSynthesis?.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="pt-BR";u.rate=.92;u.pitch=.88;window.speechSynthesis?.speak(u)}catch{}};
const cinematicTone=()=>{try{const C=window.AudioContext||(window as any).webkitAudioContext;if(!C)return;const c=new C();const now=c.currentTime;[220,330,440,660].forEach((f,i)=>{const o=c.createOscillator();const g=c.createGain();o.type="sine";o.frequency.value=f;o.connect(g);g.connect(c.destination);g.gain.setValueAtTime(.0001,now+i*.11);g.gain.exponentialRampToValueAtTime(.045,now+i*.11+.03);g.gain.exponentialRampToValueAtTime(.0001,now+i*.11+.65);o.start(now+i*.11);o.stop(now+i*.11+.7)});setTimeout(()=>c.close(),1400)}catch{}};

export function JarvisOS({go,addApproval}:Props){
 const[status,setStatus]=useState("READY");const[plan,setPlan]=useState<JarvisActionPlan|null>(null);const[logs,setLogs]=useState<Log[]>(load);const[thinking,setThinking]=useState(false);const[time,setTime]=useState(new Date());const[voice,setVoice]=useState(false);const[ambient,setAmbient]=useState(()=>localStorage.getItem("jarvis.ambient")!=="off");const[music,setMusic]=useState<{title:string;videoId:string}|null>(null);const[musicLoading,setMusicLoading]=useState(false);
 const[name,setName]=useState(()=>localStorage.getItem("jarvis.user.name")||"");const[identityOpen,setIdentityOpen]=useState(()=>!localStorage.getItem("jarvis.identity.setup"));const[faceReady,setFaceReady]=useState(false);const[faceChecking,setFaceChecking]=useState(false);const[stream,setStream]=useState<MediaStream|null>(null);const videoRef=useRef<HTMLVideoElement>(null);
 useEffect(()=>{const id=setInterval(()=>setTime(new Date()),1000);return()=>clearInterval(id)},[]);
 const recognitionRef=useRef<any>(null);const voiceActiveRef=useRef(false);const awaitingCommandRef=useRef(false);
 useEffect(()=>()=>{voiceActiveRef.current=false;try{recognitionRef.current?.stop()}catch{}},[]);
 const startVoice=()=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){push("Reconhecimento de voz não suportado neste navegador.","GUARD");speak("Reconhecimento de voz não é suportado neste navegador.");return}if(voiceActiveRef.current)return;const r=new SR();recognitionRef.current=r;r.lang="pt-BR";r.continuous=true;r.interimResults=false;voiceActiveRef.current=true;setVoice(true);setStatus("LISTENING");push("Escuta de voz ativada. Diga Jarvis para chamar o núcleo.","VOICE");r.onresult=(e:any)=>{for(let i=e.resultIndex;i<e.results.length;i++){if(!e.results[i].isFinal)continue;const heard=String(e.results[i][0]?.transcript||"").trim();if(!heard)continue;const wake=/^(?:ei\\s+|hey\\s+)?jarvis(?:[,.! ]|$)/i.test(heard);if(!wake&&!awaitingCommandRef.current)continue;const command=heard.replace(/^(?:ei\\s+|hey\\s+)?jarvis[,.! ]*/i,"").trim();if(!command){awaitingCommandRef.current=true;setStatus("AWAITING COMMAND");speak("Sim?");continue}awaitingCommandRef.current=false;run(command)}};r.onerror=()=>{if(voiceActiveRef.current)setStatus("LISTENING")};r.onend=()=>{if(voiceActiveRef.current){try{r.start()}catch{}}};try{r.start()}catch{voiceActiveRef.current=false;setVoice(false);setStatus("READY");push("Não foi possível iniciar o microfone.","GUARD")}};
 const stopVoice=()=>{voiceActiveRef.current=false;awaitingCommandRef.current=false;try{recognitionRef.current?.stop()}catch{}recognitionRef.current=null;setVoice(false);setStatus("READY");push("Escuta de voz pausada.","VOICE")};
 useEffect(()=>{if(videoRef.current&&stream)videoRef.current.srcObject=stream},[stream]);
 useEffect(()=>()=>{stopJarvisAmbient()},[]);
 const push=(text:string,kind="SYSTEM")=>{const x={id:crypto.randomUUID(),time:new Date().toLocaleTimeString("pt-BR"),text,kind};setLogs(v=>{const n=[x,...v];save(n);return n})};
 const enableAmbient=async()=>{const ok=await startJarvisAmbient();if(ok){setAmbient(true);localStorage.setItem("jarvis.ambient","on");push("Trilha ambiente contínua ativada.","AUDIO")}else{setAmbient(false);push("Áudio ambiente indisponível neste navegador.","GUARD")}};
 const toggleAmbient=async()=>{if(ambient){await stopJarvisAmbient();setAmbient(false);localStorage.setItem("jarvis.ambient","off");push("Trilha ambiente pausada.","AUDIO")}else await enableAmbient()};
 const beginIdentity=async()=>{if(!name.trim())return;localStorage.setItem("jarvis.user.name",name.trim());setFaceChecking(true);cinematicTone();await enableAmbient();push("Inicializando sessão de identidade local.","IDENTITY");try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user"},audio:false});setStream(s);setFaceReady(true);await new Promise(r=>setTimeout(r,900));push("Câmera autorizada. Nenhuma imagem foi enviada ou salva.","IDENTITY")}catch{push("Câmera não autorizada. A sessão continuará sem verificação facial.","GUARD")}setFaceChecking(false);setIdentityOpen(false);localStorage.setItem("jarvis.identity.setup","1");setStatus("READY");setTimeout(()=>{speak(`Bom te ver, ${name.trim()}. JARVIS online.`);startVoice()},350)};
 const closeCamera=()=>{stream?.getTracks().forEach(t=>t.stop());setStream(null)};
 const playMusic=async(query:string)=>{const q=query.trim();if(!q)return;setMusicLoading(true);push("Procurando música: "+q,"AUDIO");const base=localStorage.getItem("az:executorUrl")||"http://localhost:8787";try{const r=await fetch(base.replace(/\/$/,"")+"/music/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:q}),signal:AbortSignal.timeout(25000)});if(!r.ok)throw new Error("Não consegui localizar essa música.");const d=await r.json();if(!d.videoId)throw new Error("Nenhuma versão reproduzível encontrada.");setMusic({title:d.title||q,videoId:d.videoId});push("Tocando em segundo plano: "+(d.title||q),"AUDIO");speak("Tocando "+(d.title||q));}catch(e){push(e instanceof Error?e.message:"Falha ao procurar música.","GUARD");speak("Não consegui encontrar essa música.")}finally{setMusicLoading(false)}}; const research=async(query:string)=>{const base=localStorage.getItem("az:executorUrl")||"http://localhost:8787";try{const r=await fetch(base.replace(/\/$/,"")+"/research",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query}),signal:AbortSignal.timeout(25000)});if(!r.ok)throw new Error("Worker de pesquisa indisponível");const d=await r.json();const results=Array.isArray(d.results)?d.results:[];if(!results.length){push("Nenhum resultado encontrado para: "+query,"RESEARCH");speak("Não encontrei resultados relevantes.");return}results.slice(0,5).forEach((x:any,i:number)=>push((i+1)+". "+x.title+" — "+x.snippet,"RESEARCH"));speak("Encontrei "+results.length+" resultados. Os primeiros são: "+results.slice(0,3).map((x:any)=>x.title).join(". "));}catch(e){push(e instanceof Error?e.message:"Falha na pesquisa.","GUARD");speak("Não consegui acessar o pesquisador local.")}}; const run=async(input:string)=>{if(!input.trim()||thinking)return;setThinking(true);setStatus("ANALYZING");push(input,"YOU");const remembered=rememberIfImportant(input);if(remembered)push("Memória importante registrada: "+remembered.content,"MEMORY");const normalized=input.toLowerCase().normalize("NFD").replace(/[\\u0300-\\u036f]/g,"");const musicMatch=input.match(/^(?:jarvis[, ]*)?(?:toque|toca|coloque|põe|poe|reproduza|reproduzir|play)\\s+(?:a música |a musica |música |musica )?(.+)$/i);if(musicMatch?.[1]){await playMusic(musicMatch[1]);setStatus("READY");setThinking(false);return}if(normalized.includes("noticias")||normalized.includes("notícias")){await research("notícias de hoje Brasil tecnologia negócios");setStatus("READY");setThinking(false);return}const base=localStorage.getItem("az:executorUrl")||"http://localhost:8787";const p=await createActionPlanWithAI(input,base);
  if(!p){const gap=studyCapabilityGap(input);setStatus("CAPABILITY GAP");push("Não consigo executar isso ainda. Estudei como essa capacidade poderia ser adicionada e deixei uma proposta aguardando sua permissão.","EVOLUTION");push(gap.title+" — "+gap.proposedChange,"EVOLUTION");go("/evolucao");setThinking(false);return}
  setPlan(p);push(p.summary,"PLAN");setStatus(p.requiresApproval?"AWAITING APPROVAL":"EXECUTING");
  for(const a of p.actions){if(a.type==="navigate"){go(a.path);push("Navegando para "+a.path,"ACTION")}
   if(a.type==="worker_health"){try{const h=await fetch(base+"/health",{signal:AbortSignal.timeout(3000)});const d=await h.json();push("Worker conectado: "+d.status,"ACTION")}catch{push("Worker local indisponível.","GUARD")}}
   if(a.type==="research_web"){await research(a.query);push("Pesquisa concluída: "+a.label,"RESEARCH")}
   if(a.type==="delegate"){const t=multiAgentRuntime.submit(a.goal);push("Missão delegada ao agente runtime: "+t.id.slice(0,8),"AGENT")}
   if(a.type==="open_url"||a.type==="inspect_site"){addApproval({id:crypto.randomUUID(),type:"execução de navegador",title:a.label,description:"Ação externa preparada pelo Action Planner. Requer aprovação explícita.",createdAt:new Date().toISOString(),status:"pending",execution:{type:a.type,url:a.url}});push("Ação externa bloqueada até aprovação.","GUARD");go("/aprovacoes")}
  }setStatus(p.requiresApproval?"AWAITING APPROVAL":"READY");setThinking(false)
 };
 const unknown=discoverUnknown();
 return <div className="jarvisOS"><div className="jarvisOSNoise"/>
  {identityOpen&&<div className="jarvisIdentityGate"><div className="jarvisIdentityBox"><button className="identityClose" onClick={()=>{setIdentityOpen(false);localStorage.setItem("jarvis.identity.setup","1")}}><X size={16}/></button><div className="identityOrb"><UserRound size={25}/><span/></div><span className="eyebrow">FIRST CONTACT // LOCAL IDENTITY</span><h1>Como devo te chamar?</h1><p>Escolha o nome que JARVIS usará para falar com você. A câmera é opcional e fica somente no dispositivo durante esta sessão.</p><div className="identityName"><UserRound size={16}/><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Seu nome ou apelido"/></div><div className={"faceCheck "+(faceReady?"ready":"")}><Camera size={17}/><div><b>{faceChecking?"VERIFICANDO CÂMERA...":faceReady?"CÂMERA PRONTA":"CÂMERA OPCIONAL"}</b><small>Sem upload. Sem armazenamento de imagem.</small></div></div><button className="identityStart" disabled={!name.trim()||faceChecking} onClick={beginIdentity}>{faceChecking?"INICIALIZANDO...":"ENTRAR NO JARVIS"} <ChevronRight size={15}/></button></div></div>}
  <header className="jarvisOSHeader"><div className="jarvisOSBrand"><div className="jarvisOSMark"><Radio size={18}/></div><div><b>J.A.R.V.I.S.</b><span>PERSONAL INTELLIGENCE OPERATING SYSTEM</span></div></div><div className="jarvisOSWelcome">{name&&<><UserRound size={12}/> {name.toUpperCase()}</>}</div><div className="jarvisOSClock">{time.toLocaleTimeString("pt-BR")}<small>LOCAL SESSION</small></div><button className="jarvisOSExit" onClick={()=>{closeCamera();stopJarvisAmbient();go("/")}}>AGENTE ZERO <ChevronRight size={13}/></button></header>
  <div className="jarvisOSGrid"><aside className="jarvisOSRail"><button onClick={()=>go("/jarvis")} className="active"><BrainCircuit/><span>CORE</span></button><button onClick={()=>go("/runtime")}><Network/><span>AGENTS</span></button><button onClick={()=>go("/visao")}><Eye/><span>VISION</span></button><button onClick={()=>go("/memoria")}><Activity/><span>MEMORY</span></button><button onClick={()=>go("/aprovacoes")}><Shield/><span>GUARD</span></button><button onClick={()=>go("/execucao")}><Terminal/><span>OPS</span></button></aside>
   <main className="jarvisOSMain"><div className="jarvisOSTelemetry"><span>CORE <b>ONLINE</b></span><span>LOCAL <b>ENCRYPTED</b></span><span>GUARD <b>DEFAULT DENY</b></span><span>MODE <b>HUMAN IN LOOP</b></span></div>
    <section className={"jarvisReactor "+(thinking?"reacting":"")}><div className="reactorOrbit o1"/><div className="reactorOrbit o2"/><div className="reactorOrbit o3"/><div className="reactorCore"><BrainCircuit size={32}/><b>{status}</b><small>JARVIS CORE</small></div></section>
    <section className="jarvisMission"><span className="eyebrow">VOICE INTERFACE // ACTION PLANNER</span><h1>{thinking?"Deixe-me estruturar isso.":name?`Olá, ${name}. O que vamos fazer?`:"O que você quer que eu descubra?"}</h1><p>JARVIS funciona por voz. Diga <b>“Jarvis”</b> e depois seu comando. Ele interpreta o objetivo, cria um plano e pede autorização antes de ações externas.</p><div className={"jarvisVoiceCommand "+(voice?"active":"")}><div className="voicePulse"><Mic size={24}/></div><div><strong>{voice?(awaitingCommandRef.current?"OUVINDO SEU COMANDO":"ESCUTA ATIVA"):"VOZ DESATIVADA"}</strong><span>{voice?"Diga “Jarvis” e fale naturalmente.":"Ative a voz para começar."}</span></div><button onClick={voice?stopVoice:startVoice} disabled={thinking}><Mic size={15}/>{voice?"PAUSAR VOZ":"ATIVAR VOZ"}</button></div></section>
    <section className="jarvisPanels"><div className="jarvisPanel"><div className="jPanelTitle"><span>NEURAL PLAN</span><b>{plan?Math.round(plan.confidence*100)+"% CONFIDENCE":"STANDBY"}</b></div>{plan?<><h2>{plan.summary}</h2><p>{plan.reason||"Plano gerado pelo Action Planner."}</p><div className="jSteps">{plan.actions.map((a,i)=><div key={i}><i>{String(i+1).padStart(2,"0")}</i><span>{a.label}</span><small>{a.type.replaceAll("_"," ")}</small></div>)}</div></>:<div className="jEmpty">Nenhuma missão ativa. O núcleo está observando o contexto autorizado.</div>}</div>
     <div className="jarvisPanel"><div className="jPanelTitle"><span>LIVE EVENT STREAM</span><b>{logs.length} EVENTS</b></div><div className="jLogs">{logs.slice(0,7).map(l=><div key={l.id}><time>{l.time}</time><strong>{l.kind}</strong><span>{l.text}</span></div>)}</div></div></section>
    <section className="jarvisBottom"><div><span className="eyebrow">UNKNOWN ENGINE</span><b>{unknown?"ENCONTREI ALGO PARA INVESTIGAR":"SCANNING SYSTEM STATE"}</b><p>{unknown?.title||"Observando conexões entre memória, tarefas, oportunidades e habilidades."}</p></div><button onClick={()=>run("JARVIS, me surpreenda")}>SURPRISE ME <Zap size={14}/></button><button onClick={()=>go("/evolucao")}>EVOLUTION <Zap size={14}/></button><div className="jHealth"><span><LockKeyhole size={13}/> APPROVAL GATE</span><span><Volume2 size={13}/> VOICE READY</span><span><Camera size={13}/> {faceReady?"CAMERA READY":"CAMERA OPTIONAL"}</span><button className={ambient?"ambientOn":""} onClick={toggleAmbient}><Music2 size={13}/> {ambient?"AMBIENT ON":"AMBIENT OFF"}</button><button onClick={voice?stopVoice:startVoice}><Mic size={13}/> {voice?"VOICE ACTIVE":"START VOICE"}</button></div></section>
   </main></div>
  {stream&&<div className="jarvisFaceMini"><video ref={videoRef} autoPlay muted playsInline/><div><Camera size={11}/> LOCAL FACE CHECK <button onClick={closeCamera}>STOP</button></div></div>}{music&&<div style={{position:"fixed",right:18,bottom:18,width:320,maxWidth:"calc(100vw - 36px)",zIndex:80,border:"1px solid rgba(255,255,255,.14)",borderRadius:16,overflow:"hidden",background:"rgba(7,10,16,.94)",boxShadow:"0 18px 50px rgba(0,0,0,.45)",backdropFilter:"blur(14px)"}}><div style={{padding:"10px 12px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:8}}><div style={{minWidth:0}}><div style={{fontSize:10,letterSpacing:1.5,opacity:.6}}>JARVIS AUDIO</div><b style={{display:"block",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{music.title}</b></div><button onClick={()=>setMusic(null)} style={{background:"transparent",border:0,color:"inherit",cursor:"pointer"}}><X size={15}/></button></div><iframe title={"JARVIS Music — "+music.title} width="100%" height="180" src={"https://www.youtube.com/embed/"+music.videoId+"?autoplay=1&rel=0&modestbranding=1"} allow="autoplay; encrypted-media; picture-in-picture" style={{display:"block",border:0}}/><div style={{padding:"8px 12px",fontSize:10,opacity:.58}}>A reprodução usa o player oficial incorporado do YouTube.</div></div>}
 </div>
}